pipeline:
  name: demo-1
  identifier: demo1
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  trigger:
    branches:
      - main
  stages:
    - name: YourFirstStage
      jobs:
        - name: YourFirstJob
          steps:
            - type: Run
              identifier: build_go_app
              name: Build Go App
              spec:
                command: |-
                  echo "Welcome to Harness CI"
                  go build
                  go test check syntax
