pipeline:
  name: demo-1
  identifier: demo1
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  trigger:
    branches:
      - main
  stages:
    - name: YourFirstStage
      jobs:
        - name: YourFirstJob
          steps:
            - script:
                name: YourScript
                code: |
                  # Add your commands here
    - name: YourSecondStage
      jobs:
        - name: YourSecondJob
          steps:
            - script:
                name: YourScript
                code: |
                  # Add your commands here
